### ISSUE TITLE
[Performance] Studies runs better as isolated app than inside gallery shell

### ISSUE THREAD

**Issue by JoseAlba** [material-components/material-components-flutter-gallery#555] opened 2020-02-27 16:29 UTC
On all (Rally, shine, fortnightly etc) apps the initial load is janky
Second time loading is better but still a bit slow

Also, let's check on deployment settings: it may be that he (cc @ferhatb) had it compiled on a different build or with different flags (CanvasKit?) "

**Comment by guidezpl** [comment] 2020-03-17 16:13
Duplicate of #556

**Closed by guidezpl** 2020-03-17 16:13 UTC
