### ISSUE TITLE
Shadows are large on web

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#308] opened 2019-11-21 09:59 UTC
## Acceptance Criteria
* Workaround until Flutter web team fixes this, set shadows to smaller elevation if isWeb

**Comment by rami-a** [comment] 2020-02-25 16:13
Due to https://github.com/flutter/flutter/issues/32215

**Comment by willlarche** [comment] 2020-03-10 15:07
This PR has landed. Ready for retest.

**Comment by yjbanov** [comment] 2020-03-10 19:35
I relanded the fix. Watching the engine roll now to make sure it sticks.

**Comment by perclasson** [comment] 2020-03-12 11:11
The shadows are no longer larger on web. They are slightly darker than on for example macOS, see comparison:
*Web*
<img width="1435" alt="Screenshot 2020-03-12 at 12 08 41" src="https://user-images.githubusercontent.com/1770678/76515687-512d9f00-645a-11ea-902e-3f054044933a.png">

*macOS*
<img width="1532" alt="Screenshot 2020-03-12 at 12 10 42" src="https://user-images.githubusercontent.com/1770678/76515831-9782fe00-645a-11ea-9f14-4c7f79b2c40e.png">

**Comment by perclasson** [comment] 2020-03-12 11:18
From [comment](https://github.com/flutter/flutter/issues/32215#issuecomment-589893161) this seems to be expected behaviour as the shadows are not expected to look exactly the same as on mobile. I'll close the ticket as fixed.

**Closed by perclasson** 2020-03-12 11:18 UTC
Labels: P2, bug
