### ISSUE TITLE
Bringing up the keyboard on iPad causes the app to change to mobile layout (2)

### ISSUE THREAD

**Issue by rami-a** [material-components/material-components-flutter-gallery#501] opened 2019-12-12 16:56 UTC
## Acceptance Criteria
* All screens stay in desktop layout even when keyboard is up on tablet

**Comment by rami-a** [comment] 2019-12-16 15:00
I'm unable to reproduce this but if someone else can please update the ticket with repro steps

**Comment by perclasson** [comment] 2020-01-28 15:38
I am also unable to reproduce this on any simulator, and a physical iPad and Android tablet. I'll close this ticket as fixed until we see this again.

**Closed by perclasson** 2020-01-28 15:38 UTC
Labels: P2, bug
